// frontend/src/views/Register.vue
<template>
    <div>
        <h3 class="text-h3 mb-2 mt-8 text-center">Register</h3>
        <h5 class="text-h5 mb-4 text-center">
            Create an account for ddueruem-web
        </h5>
        <v-row justify="center" align="center">
            <v-col cols="12" sm="5">
                <v-alert v-model="error.isError" v-if="error.isError" dismissible dense outlined type="error">Error: {{ error.msg }}
                </v-alert>
                <v-form ref="form" v-model="valid" lazy-validation v-on:submit="onSubmit">
                    <v-text-field v-model="email" :rules="emailRules" label="E-mail" required></v-text-field>

                    <v-text-field v-model="password" :append-icon="show1 ? 'mdi-eye' : 'mdi-eye-off'"
                        :rules="passwordRules" :type="show1 ? 'text' : 'password'" name="input-10-1" label="Password"
                        hint="At least 8 characters" counter @click:append="show1 = !show1">
                    </v-text-field>

                    <v-text-field v-model="passwordConfirmation" :append-icon="show2 ? 'mdi-eye' : 'mdi-eye-off'"
                        :rules="passwordRules" :type="show2 ? 'text' : 'password'" name="input-10-1" label="Password"
                        hint="At least 8 characters" counter @click:append="show2 = !show2">
                    </v-text-field>

                    <p>
                        By registering you accept our <router-link to="/dsgvo" target="_blank">DSGVO</router-link>
                        (german
                        language).
                    </p>

                    <v-btn :disabled="!isReady" color="primary" class="mr-4" :loading="loading" type="submit">
                        Register
                    </v-btn>
                </v-form>
            </v-col>

        </v-row>
    </div>

</template>

<script lang="ts">
import Vue from "vue"
import { Register } from '../../types'
import AuthService from "@/services/auth.service";

export default Vue.extend({
    name: 'Register',

    components: {},

    props: {},

    data: () => ({
        email: "" as Register["email"],
        password: "" as Register["password"],
        passwordConfirmation: "" as Register["passwordConfirmation"],
        loading: false as Register["loading"],

        valid: false,
        emailRules: [
            (v: string) => !!v || 'E-mail is required',
            (v: string) => /.+@.+\..+/.test(v) || 'E-mail must be valid',
        ],
        passwordRules: [
            (v: string) => !!v || 'Required.',
            (v: string) => v.length >= 8 || 'Min 8 characters',
            /* emailMatch: () => (`The email and password you entered don't match`), */
        ],
        show1: false,
        show2: false,
        error: { isError: false, msg: "" }
    }),

    computed: {
        isReady(): boolean {
            return this.valid && this.email != "" && this.password != "" && this.passwordConfirmation != ""
        }
    },

    methods: {
        onSubmit(e: { preventDefault: () => void }) {
            e.preventDefault();
            if (
                this.email != ""
                && this.password != ""
                && this.passwordConfirmation != ""
                && this.password === this.passwordConfirmation
            ) {
                this.loading = true;
                AuthService.register(
                    this.email,
                    this.password,
                    this.passwordConfirmation,
                ).then(
                    () => {
                        /* Modal.fire({
                            icon: 'success',
                            title: 'Register successful, please check your mail',
                            toast: true,
                            position: 'top-right',
                            showConfirmButton: false,
                            timer: 1500,
                            timerProgressBar: true,
                        }).then(() => {
                            window.location.replace('/login');
                        }); */
                        this.error = { isError: false, msg: "" }
                        this.loading = false;
                        console.log("Success")
                    },
                    (error) => {
                        /* Modal.fire({
                            icon: 'error',
                            title: 'Error!!',
                            text: `Something went wrong while registering! ${error.toString()}`,
                        }); */
                        this.error = { isError: true, msg: error.response.data }
                        this.loading = false;
                        console.log(error.response.data)
                    },
                );
            }
        }
    },
});
</script>

<style scoped>
</style>

// frontend/src/components/register.component.tsx
import React, { Component } from "react";
import { Button, Form } from "react-bootstrap";
import Swal from "sweetalert2";
import withReactContent from "sweetalert2-react-content";
import AuthService from "../services/auth.service";

const MySwal = withReactContent(Swal);

type Props = {};

type State = {
  email?: string;
  password?: string;
  passwordConfirmation?: string;
  loading: boolean;
};

export default class Register extends Component<Props, State> {
  state: State = {
    email: undefined,
    password: undefined,
    passwordConfirmation: undefined,
    loading: false,
  };

  onEmailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const email = e.target as HTMLInputElement;
    this.setState({ email: email.value });
  };

  onPasswordChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const password = e.target as HTMLInputElement;
    this.setState({ password: password.value });
  };

  onPasswordConfirmationChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const passwordConfirmation = e.target as HTMLInputElement;
    this.setState({ passwordConfirmation: passwordConfirmation.value });
  };

  isReady = () => {
    return (
      this.state.email &&
      this.state.password &&
      this.state.passwordConfirmation &&
      this.state.password === this.state.passwordConfirmation
    );
  };

  onSubmit = () => {
    if (
      this.state.email &&
      this.state.password &&
      this.state.passwordConfirmation &&
      this.state.password === this.state.passwordConfirmation
    ) {
      AuthService.register(this.state.email, this.state.password).then(
        () => {
          MySwal.fire({
            icon: "success",
            title: "Register successful, please check your mail",
            toast: true,
            position: "top-right",
            showConfirmButton: false,
            timer: 1500,
            timerProgressBar: true,
          }).then(() => {
            window.location.replace("/");
          });
        },
        (error) => {
          this.setState({ loading: false });
          MySwal.fire({
            icon: "error",
            title: "Error!!",
            text: `Something went wrong while registering! ${error.toString()}`,
          });
        }
      );
    }
  };

  render() {
    return (
      <div>
        <Form.Group className='mb-3'>
          <Form.Label>Email</Form.Label>
          <Form.Control
            type='email'
            placeholder='Email'
            onChange={this.onEmailChange}
          />
        </Form.Group>
        <Form.Group className='mb-3'>
          <Form.Label>Password</Form.Label>
          <Form.Control type='password' onChange={this.onPasswordChange} />
        </Form.Group>
        <Form.Group className='mb-3'>
          <Form.Label>Password Confirmation</Form.Label>
          <Form.Control
            type='password'
            onChange={this.onPasswordConfirmationChange}
          />
        </Form.Group>
        <Button
          variant='primary'
          type='button'
          disabled={!this.isReady() || this.state.loading ? true : undefined}
          onClick={this.onSubmit}
        >
          {this.state.loading && (
            <span className='spinner-border spinner-border-sm' />
          )}
          Register!
        </Button>
      </div>
    );
  }
}
