// frontend_react/src/routes/Files/FileCreate.tsx
import React, { Component } from 'react';
import {
  Button, Container, Form, Row,
} from 'react-bootstrap';
import CreatableSelect from 'react-select/creatable';
import { default as Modal } from '../../components/Modal';
import api from '../../services/api.service';
import isNumeric from '../../services/numbers.service';

const API_URL = process.env.REACT_APP_DOMAIN;

type Props = {};

type State = {
  label: string;
  description?: string;
  file?: File;
  gottenLicenses: Array<{label: string; value: string}>;
  gottenTags: Array<{ label: string; value: string }>;
  gottenFiles: Array<{ value: number; label: string }>;
  gottenFamilies: Array<{ value: number; label: string }>;
  newVersionOf: string;
  featureFamily: string;
  license: string;
  tags: string;
  loading: boolean;
  legalShare: boolean;
  userData: boolean;
  openSource: boolean;
  newVersionOfSelection: boolean;
  featureModelFamilySelection: boolean;
};

/**
 * This route is responsible for the file upload.
 * It is only visible for authenticated users.
 */
export default class FileCreate extends Component<Props, State> {
  /**
   * Constructor for file creation. It uses two fetch calls
   * to get all available tags and all available files.
   * @param {Props} props are empty
   */
  constructor(props: Props | Readonly<Props>) {
    super(props);
    this.getTags();
    this.getNewVersionOf();
    this.getFamilies();
    this.getLicenses();

    this.state = {
      label: '',
      description: undefined,
      file: undefined,
      gottenLicenses: [],
      gottenTags: [],
      gottenFiles: [],
      gottenFamilies: [],
      tags: '',
      newVersionOf: '---',
      featureFamily: '---',
      license: '',
      loading: false,
      legalShare: false,
      userData: false,
      openSource: false,
      featureModelFamilySelection: true,
      newVersionOfSelection: true,
    };
  }

  getTags = async () => {
    await api.get(`${API_URL}tags/`).then((response) => {
      let tags = response.data;
      tags = tags.map((tag: { id: number; label: string }) => ({
        value: tag.id,
        label: tag.label,
      }));
      this.setState({ gottenTags: tags });
      return tags;
    });
  };

  getFamilies = async () => {
    await api.get(`${API_URL}families/`).then((response) => {
      let families = response.data;
      families = families.map((family: { id: number; label: string }) => ({
        value: family.id,
        label: family.label,
      }));
      this.setState({ gottenFamilies: families });
      return families;
    });
  };

  getLicenses = () => {
    api.get(`${API_URL}licenses/`).then((response) => {
      let licenses = response.data;
      licenses = licenses.map((license: { id: number; label: string }) => ({
        value: license.id,
        label: license.label,
      }));
      this.setState({ gottenLicenses: licenses });
      return licenses;
    });
  };

  getNewVersionOf = () => {
    api.get(`${API_URL}files/`).then((response) => {
      let files = response.data;
      files = files.map((file: { id: number; label: string }) => ({
        value: file.id,
        label: file.label,
      }));
      this.setState({ gottenFiles: files });
    });
  };

  getTagsWithTagId = (options: any) => options.map((option: any) => {
    let id = option.value;

    if (!Number.isInteger(id)) {
      const newElement = this.state.gottenTags.find((element) => (element.label === option.value));

      if (newElement && newElement.value) {
        id = newElement.value;
      }
    }

    return {
      id,
      label: option.label,
    };
  });

  onTagChange = (options: any) => {
    if (!this.state.gottenTags.some((e) => options[options.length - 1].label === e.label)) {
      api
        .post(`${API_URL}tags/`, { label: options[options.length - 1].label, description: '' })
        .then(async () => {
          await this.getTags();

          const tags = this.getTagsWithTagId(options);

          this.setState({
            tags,
          });
        });
    } else {
      const tags = this.getTagsWithTagId(options);

      this.setState({
        tags,
      });
    }
  };

  onLabelChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const label = e.target as HTMLInputElement;
    this.setState({ label: label.value });
  };

  onDescriptionChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const description = e.target as HTMLInputElement;
    this.setState({ description: description.value });
  };

  onFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target as HTMLInputElement;
    if (file.files) {
      this.setState({ file: file.files[0] });
    }
  };

  onNewVersionOfChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const newVersionOf = e.target as HTMLSelectElement;
    this.setState({ newVersionOf: newVersionOf.value });

    if (newVersionOf.value === '---') {
      this.setState({ featureModelFamilySelection: true });
    } else {
      this.setState({ featureModelFamilySelection: false });
    }
  };

  getFamilyWithFamilyId = (option: any) => {
    let id = option.value;

    if (!isNumeric(id)) {
      const newElement = this.state.gottenFamilies
        .find((element) => (element.label === option.value));

      if (newElement && newElement.value) {
        id = newElement.value;
      }
    }

    return id;
  };

  onNewFamilyChange = (option: any) => {
    if (option.value === '') {
      this.setState({ newVersionOfSelection: true });
    } else {
      this.setState({ newVersionOfSelection: false });
    }

    if (!this.state.gottenFamilies.some((e) => option.label === e.label)) {
      api
        .post(`${API_URL}families/`, { label: option.label, description: '' })
        .then(async () => {
          await this.getFamilies();

          const featureFamily = this.getFamilyWithFamilyId(option);

          this.setState({
            featureFamily,
          });
        });
    } else {
      const featureFamily = this.getFamilyWithFamilyId(option);

      this.setState({
        featureFamily,
      });
    }
  };

  onLicenseChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const license = e.target as HTMLSelectElement;
    this.setState({ license: license.value });
  };

  isReady = () => this.state.tags
    && !(this.state.license === '---')
    && this.state.label
    && this.state.file
    && this.state.description
    && this.state.legalShare
    && this.state.userData
    && this.state.openSource
    && this.state.license !== '---'
    && this.state.license
    && !(this.state.featureFamily === '---' && this.state.newVersionOf === '---');

  onSubmit = (e: { preventDefault: () => void }) => {
    e.preventDefault();
    if (
      this.state.tags
      && this.state.label
      && this.state.file
      && this.state.description
      && this.state.legalShare
      && this.state.userData
      && this.state.openSource
      && this.state.license !== '---'
      && !(this.state.featureFamily === '---' && this.state.newVersionOf === '---')
    ) {
      this.setState({ loading: true });
      const data = new FormData();

      data.append('label', this.state.label);
      console.log('LABEL');
      console.log(this.state.label);
      data.append('description', this.state.description);
      console.log('DESCRIPTION');
      console.log(this.state.description);
      data.append('local_file', this.state.file);
      console.log('FILE');
      console.log(this.state.file);
      data.append('license', this.state.license);
      console.log('LICENSE');
      console.log(this.state.license);
      if (this.state.newVersionOf !== '---') {
        data.append('new_version_of', this.state.newVersionOf);
        console.log('NEW VERSION OF');
        console.log(this.state.newVersionOf);
      }
      if (this.state.featureFamily !== '---') {
        data.append('family', this.state.featureFamily);
        console.log('FEATURE FAMILY');
        console.log(this.state.featureFamily);
      }
      data.append('tags', JSON.stringify(this.state.tags));
      console.log('TAGS');
      console.log(this.state.tags);

      api
        .post(`${API_URL}files/`, data, {
          headers: { 'Content-Type': 'multipart/form-data' },
        })
        .then(() => {
          Modal.fire({
            icon: 'success',
            title: 'Success!!',
            text: 'File was uploaded successfully!',
          }).then(() => {
            window.location.reload();
          });
        })
        .catch((error) => {
          this.setState({ loading: false });
          Modal.fire({
            icon: 'error',
            title: 'Error!!',
            text: JSON.stringify(error.message),
          });
        });
    }
  };

  /**
   * Renders the file upload form.
   * @return {JSX} the component.
   */
  render() {
    return (
      <Container>
        <Row>
          <form onSubmit={this.onSubmit}>
            <Form.Group className="mb-3">
              <Form.Label>File name</Form.Label>
              <Form.Control
                data-testid="label"
                onChange={this.onLabelChange}
                placeholder="Leave a filename"
              />
            </Form.Group>
            <Form.Group className="mb-3">
              <Form.Label>Description</Form.Label>
              <Form.Control
                data-testid="description"
                as="textarea"
                maxLength={250}
                onChange={this.onDescriptionChange}
                placeholder="Leave a comment here"
              />
            </Form.Group>
            <Form.Group className="mb-3">
              <Form.Label>File Upload</Form.Label>
              <Form.Control
                data-testid="file-upload"
                type="file"
                onChange={this.onFileChange}
                accept=".xml"
              />
            </Form.Group>
            <Form.Group className="mb-3">
              <Form.Label>License</Form.Label>
              <Form.Select data-testid="license" onChange={this.onLicenseChange} defaultValue="---">
                {this.state.gottenLicenses.map((key) => (
                  <option key={key.value} value={key.value}>
                    {key.value}
                    :
                    {key.label}
                  </option>
                ))}
                <option key="---" value="---">
                  ---
                </option>
              </Form.Select>
            </Form.Group>
            <Row>
              <Form.Group className="col-sm">
                <Form.Label>New version of</Form.Label>
                <Form.Select
                  data-testid="version"
                  onChange={this.onNewVersionOfChange}
                  disabled={!this.state.newVersionOfSelection ?? undefined}
                  defaultValue="---"
                >
                  {this.state.gottenFiles.map((key) => (
                    <option key={key.value} value={key.value}>
                      {key.value}
                      :
                      {key.label}
                    </option>
                  ))}
                  <option key="---" value="---">
                    ---
                  </option>
                </Form.Select>
              </Form.Group>
              <Form.Group className="col-sm">
                <Form.Label htmlFor="families">Feature model family</Form.Label>
                <CreatableSelect
                  isDisabled={!this.state.featureModelFamilySelection ?? undefined}
                  name="families"
                  inputId="families"
                  onChange={this.onNewFamilyChange}
                  options={this.state.gottenFamilies}
                />
              </Form.Group>
            </Row>
            <Form.Group className="mb-3">
              <Form.Label htmlFor="tags">Tags</Form.Label>
              <CreatableSelect
                isMulti
                name="tags"
                inputId="tags"
                onChange={this.onTagChange}
                options={this.state.gottenTags}
              />
            </Form.Group>
            <Form.Group className="mb-3">
              <Form.Check
                data-testid="legal-share"
                type="checkbox"
                checked={this.state.legalShare}
                onChange={() => this.setState({ legalShare: !this.state.legalShare })}
                id="legal-share"
                label="I am legally allowed to share this model"
              />
              <Form.Check
                data-testid="user-data"
                type="checkbox"
                checked={this.state.userData}
                onChange={() => this.setState({ userData: !this.state.userData })}
                id="user-data"
                label="My email and a date will always be tied to the file
                 upload (even after account deletion)"
              />
              <Form.Check
                data-testid="open-source"
                type="checkbox"
                checked={this.state.openSource}
                onChange={() => this.setState({ openSource: !this.state.openSource })}
                id="open-source"
                label="All information will be published according to your
                 chosen license"
              />
            </Form.Group>
            <Button
              variant="primary"
              type="submit"
              disabled={
                !this.isReady() || this.state.loading ? true : undefined
              }
            >
              {this.state.loading && (
                <span className="spinner-border spinner-border-sm" />
              )}
              Upload!
            </Button>
          </form>
        </Row>
      </Container>
    );
  }
}

// frontend/src/views/FileCreate.vue
<template>
  <div>
    <v-card>
      <v-card-title>
        <span class="text-h5">Upload Feature Model</span>
      </v-card-title>
      <v-card-subtitle>
        Use this form to upload a new Feature Model publicly
      </v-card-subtitle>

      <v-card-text>
        <v-container>
          <v-form ref="form" v-model="valid" lazy-validation>
            <v-row>
              <v-col cols="12" class="py-0">
                <v-text-field
                  outlined
                  dense
                  required
                  :rules="labelRules"
                  v-model="label"
                  label="File name"
                  placeholder="Leave a filename"
                  hint="Name your feature model"
                ></v-text-field>
              </v-col>
              <v-col cols="12" class="py-0">
                <v-textarea
                  outlined
                  dense
                  rows="2"
                  v-model="description"
                  label="Description"
                  placeholder="Leave a comment here"
                  counter="250"
                  :rules="descriptionRules"
                  hint="Add a description to your feature model"
                >
                </v-textarea>
              </v-col>
              <v-col cols="12" md="6" class="py-0">
                <v-file-input
                  outlined
                  chips
                  small-chips
                  required
                  dense
                  v-model="file"
                  :rules="fileRules"
                  label="File Upload"
                  accept=".xml"
                  show-size
                  hint="Select the file as .xml"
                ></v-file-input>
              </v-col>
              <v-col cols="12" md="6" class="py-0">
                <v-select
                  outlined
                  required
                  dense
                  v-model="license"
                  :rules="licenseRules"
                  :items="getLicenses"
                  label="License"
                  hint="Select the license of the feature model"
                >
                </v-select>
              </v-col>
            </v-row>
            <v-row justify="space-between" align="center">
              <v-col cols="12" md="5" class="py-0 mb-7">
                <v-autocomplete
                  :disabled="family != null"
                  outlined
                  dense
                  hide-details
                  :required="family == null"
                  v-model="newVersionOf"
                  :items="gottenFiles"
                  label="New version of"
                  hint="If your feature model is a new version of an existing one"
                ></v-autocomplete>
              </v-col>
              <v-col cols="12" md="auto" class="py-0 mb-7 text-center">
                OR
              </v-col>
              <v-col cols="12" md="5" class="py-0">
                <!-- Change back to v-combobox when new family upload is working properly -->
                <v-autocomplete
                  :disabled="newVersionOf != null"
                  :required="newVersionOf == null"
                  outlined
                  dense
                  hide-details
                  v-model="family"
                  class="mb-7"
                  :items="gottenFamilies"
                  label="Family"
                  hint="Add to or create new family"
                ></v-autocomplete>
                <v-text-field
                    v-if="isNewFamily"
                    outlined
                    hide-details
                    dense
                    v-model="newFamilyDescription"
                    label="New Family Description"
                    hint="Describe your new family"
                    class="mb-7"
                ></v-text-field>
              </v-col>
            </v-row>
            <v-row>
              <v-col cols="12" class="py-0">
                <!-- Change back to v-combobox once sequential axios requests are implemented -->
                <v-combobox
                  outlined
                  hide-details
                  v-model="tags"
                  :items="getTags"
                  label="Tags"
                  multiple
                  chips
                  small-chips
                  dense
                  hint="Choose or create tags for your feature model"
                ></v-combobox>
              </v-col>
              <v-col cols="12" class="pb-0">
                <v-checkbox
                  outlined
                  required
                  hide-details
                  v-model="legalShare"
                  label="I am legally allowed to share this model"
                  class="mt-0"
                >
                </v-checkbox>
              </v-col>
              <v-col cols="12" class="py-0">
                <v-checkbox
                  outlined
                  required
                  hide-details
                  v-model="userData"
                  label="My email and a date will always be tied to the file
                 upload (even after account deletion)"
                  class="mt-0"
                >
                </v-checkbox>
              </v-col>
              <v-col cols="12" class="py-0">
                <v-checkbox
                  outlined
                  required
                  hide-details
                  v-model="openSource"
                  label="All information will be published according to your
                 chosen license"
                  class="mt-0"
                >
                </v-checkbox>
              </v-col>
              <v-col cols="12" class="pb-0">
                <div class="d-flex">
                  <v-spacer></v-spacer>
                  <v-btn color="primary" text @click="close"> Cancel </v-btn>
                  <v-btn
                    color="primary"
                    @click="upload"
                    :disabled="!valid || !openSource || !userData || !legalShare"
                    :loading="loading"
                  >
                    Upload
                  </v-btn>
                </div>
              </v-col>
            </v-row>
          </v-form>
        </v-container>
      </v-card-text>
    </v-card>
  </div>
</template>

<script>
import Vue from "vue";
import api from "@/services/api.service";

const API_URL = process.env.VUE_APP_DOMAIN;

export default Vue.extend({
  name: "FileCreate",

  components: {},

  props: {},

  data: () => ({
    valid: false,

    label: "",
    labelRules: [(v) => !!v || "Label is required"],

    description: "",
    descriptionRules: [(v) => !!v || "Description is required", (v) => v.length <= 250 || "Max 250 characters please"],

    file: null,
    fileRules: [(v) => !!v || "File is required"],

    gottenLicenses: [],
    license: "",
    licenseRules: [(v) => !!v || "License is required"],

    gottenFamilies: [],
    gottenFiles: [],
    newVersionOf: null,

    family: null,
    newFamilyDescription: "",
    isNewFamily: false,

    gottenTags: [],
    tags: null,

    legalShare: false,
    userData: false,
    openSource: false,

    loading: false,

    /* gottenFiles: [],
    newVersionOf: "",
    featureFamily: "",
    tags: "",
    loading: false,
    newVersionOfSelection: false,
    featureModelFamilySelection: false, */
  }),

  watch: {
    "$store.state.licenses": function () {
      this.gottenLicenses = this.$store.state.licenses;
    },
    "$store.state.tags": function () {
      this.gottenTags = this.$store.state.tags;
    },
    "$store.state.families": function () {
      this.gottenFamilies = this.$store.state.families;
    },
    "$store.state.files": function () {
      this.gottenFiles = this.$store.state.files;
    },
    family: function(newValue) {
      console.log(newValue)
      if (typeof(newValue) == "string") {
        /*console.log("its a string")
        console.log(!this.gottenFamilies.map(x => x.text).includes(newValue))*/
        this.isNewFamily = !this.gottenFamilies.map(x => x.text).includes(newValue)
      } else if (typeof(newValue) == "object" && newValue != null) {
        /*console.log("its an object")
        console.log(!this.gottenFamilies.map(x => x.text).includes(newValue.text))*/
        this.isNewFamily = !this.gottenFamilies.map(x => x.text).includes(newValue.text)
      } else {
        this.isNewFamily = false
      }
    }
  },

  computed: {
    getLicenses() {
      const licenses = [];
      for (let i = 0; i < this.gottenLicenses.length; i++) {
        const element = this.gottenLicenses[i];
        licenses.push({ text: element.label, value: element.id });
      }
      return licenses;
    },
    getFamilies() {
      const families = [];
      for (let i = 0; i < this.gottenFamilies.length; i++) {
        const element = this.gottenFamilies[i];
        if (!element.owner) {
          continue;
        }
        families.push({ text: element.label, value: element.id });
      }
      return families;
    },
    getFiles() {
      const files = [];
      for (let i = 0; i < this.gottenFiles.length; i++) {
        /*console.log(this.gottenFiles)*/
        const element = this.gottenFiles[i];
        if (!element.owner) {
          continue;
        }
        files.push({ text: element.label, value: element.id });
      }
      return files;
    },
    getTags() {
      const tags = [];
      for (let i = 0; i < this.gottenTags.length; i++) {
        const element = this.gottenTags[i];
        tags.push({ text: element.label, value: element.id });
      }
      return tags;
    },
  },

  methods: {
    close() {
      this.$emit("close");
    },
    transferToDropdown(objects) {
      const temp = [];
      for (let i = 0; i < objects.length; i++) {
        const element = objects[i];
        if (!element.owner) {
          continue;
        }
        temp.push({ text: element.label, value: element.id });
      }
      return temp;
    },
    upload() {
      if (this.$refs.form.validate() !== false) {
        this.loading = true;
        const data = new FormData();

        data.append("label", this.label);
        console.log("LABEL");
        console.log(this.label);
        data.append("description", this.description);
        console.log("DESCRIPTION");
        console.log(this.description);
        data.append("local_file", this.file);
        console.log("FILE");
        console.log(this.file);
        data.append("license", this.license);
        console.log("LICENSE");
        console.log(this.license);
        if (this.newVersionOf !== null && this.newVersionOf) {
          data.append("new_version_of", this.newVersionOf);
          console.log("NEW VERSION OF");
          console.log(this.newVersionOf);
        }
        if (this.family !== "" && this.family) {
          if (!this.isNewFamily) {
            //change back to this.family.value when using v-combobox again
            data.append("family", this.family);
            console.log("FEATURE FAMILY (not new)")
            console.log(this.family)
          } /*else {
            api
              .post(`${API_URL}families/`, {label: this.family, description: this.newFamilyDescription})
              .then(async () => {
                await this.$store.dispatch("fetchFamilies");
                await data.append("family", null);
                console.log("FEATURE FAMILY (didnt work)")
              })
              .catch((error) => {
                this.$store.commit("updateSnackbar", {
                  message: "Error while creating new family: " + error.message,
                  variant: "error",
                  timeout: 5000,
                  show: true,
                });
                data.append("family", null);
                console.log("FEATURE FAMILY (didnt work)")
              });
          }*/
        }
        for (let i = 0; i < this.tags.length; i++) {
          this.tags[i].label = this.tags[i]["text"];
          delete this.tags[i].text;
          this.tags[i].id = this.tags[i]["value"];
          delete this.tags[i].value;
        }
        data.append("tags", JSON.stringify(this.tags));
        console.log("TAGS");
        console.log(this.tags);

        /*console.log(data)*/

        api
          .post(`${API_URL}files/`, data, {
            headers: { "Content-Type": "multipart/form-data" },
          })
          .then(() => {
            this.$store.commit("updateSnackbar", {
              message: "File uploaded successfully! Check your mails",
              variant: "success",
              timeout: 5000,
              show: true,
            });
            this.loading = false;
            this.close();
          })
          .catch((error) => {
            this.$store.commit("updateSnackbar", {
              message: "Error: " + error.message,
              variant: "error",
              timeout: 5000,
              show: true,
            });
            this.loading = false;
            this.close();
          });
      }
    },
  },

  mounted() {
    this.$store.dispatch("fetchLicenses");
    if (this.$store.state.families !== []) {
      /*console.log("already there fam")
      console.log(this.$store.state.families)*/
      this.gottenFamilies = this.$store.state.families.map(x => {return {text: x.label, value: x.id}})
    } else {
      this.$store.dispatch("fetchFamilies");
    }
    if (this.$store.state.files !== []) {
      /*console.log("already there file")
      console.log(this.$store.state.files)*/
      this.gottenFiles = this.$store.state.files.map(x => {return {text: x.label, value: x.id}})
    } else {
      this.$store.dispatch("fetchFiles");
    }
    this.$store.dispatch("fetchTags");
  },
});
</script>

<style scoped></style>
